
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jhoan P
 */
public class Agregar extends javax.swing.JFrame {
    
    public Agregar() {
        initComponents();
    }
    
    private String[][] data = new String[5][2];

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboficio = new javax.swing.JCheckBox();
        cbcomida = new javax.swing.JCheckBox();
        cblavado = new javax.swing.JCheckBox();
        cbtrabajar = new javax.swing.JCheckBox();
        btnregreso = new javax.swing.JButton();
        cbvivo = new javax.swing.JCheckBox();
        btnaceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Tareas");

        cboficio.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cboficio.setForeground(new java.awt.Color(51, 51, 51));
        cboficio.setText("Oficio");
        cboficio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboficioActionPerformed(evt);
            }
        });

        cbcomida.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbcomida.setForeground(new java.awt.Color(0, 51, 51));
        cbcomida.setText("Comida");

        cblavado.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cblavado.setForeground(new java.awt.Color(0, 51, 51));
        cblavado.setText("Lavado");

        cbtrabajar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbtrabajar.setForeground(new java.awt.Color(51, 51, 51));
        cbtrabajar.setText("Trabajar");

        btnregreso.setText("Regresar");
        btnregreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresoActionPerformed(evt);
            }
        });

        cbvivo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbvivo.setForeground(new java.awt.Color(0, 51, 51));
        cbvivo.setText("Mantenerse vivo");

        btnaceptar.setText("Aceptar");
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboficio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbcomida, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(cblavado, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(cbtrabajar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnregreso, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbvivo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnaceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboficio)
                    .addComponent(cbcomida)
                    .addComponent(cblavado)
                    .addComponent(cbtrabajar))
                .addGap(47, 47, 47)
                .addComponent(cbvivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregreso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        String cadena = " ";
        if(cboficio.isSelected()){
            cadena = cadena+cboficio.getText()+", ";
        } if(cbcomida.isSelected()){
            cadena = cadena+cbcomida.getText()+", ";
        } if(cblavado.isSelected()){
            cadena = cadena+cblavado.getText()+", "; 
        } if(cbtrabajar.isSelected()){
            cadena = cadena+cbtrabajar.getText()+", ";
        } if(cbvivo.isSelected()){
            cadena = cadena+cbvivo.getText()+", ";
        }
        JOptionPane.showMessageDialog(null, "acaba de agregar: " + cadena + "tienes un plazo de 7 días para estas");
        this.Meter();
    }//GEN-LAST:event_btnaceptarActionPerformed
    private void Limpiar(){
        data[0][0] = cboficio.getText();
        data[1][0] = cbcomida.getText();
        data[2][0] = cbtrabajar.getText();
        data[3][0] = cbvivo.getText();
        data[4][0] = cblavado.getText();
       for(int i = 0; i < 5 ; i++){
            data[i][1] = "No";
       }
    
    }
    
    private void Meter(){
        Limpiar();
        
        if(cboficio.isSelected() == true)
        {

            data[0][1] = "Yes";
        }
        if(cbcomida.isSelected() == true)
        {

            data[1][1] = "Yes";
        }
        if(cbtrabajar.isSelected() == true)
        {
            
            data[2][1] = "Yes";
        }
        if(cbvivo.isSelected() == true)
        {
           
            data[3][1] = "Yes";
        }
        if(cblavado.isSelected() == true)
        {
            data[4][1] = "Yes";
        }
        System.out.println(data[0][0]+data[0][1]+data[1][0]+data[1][1]+data[2][0]+data[2][1]+data[3][0]+data[3][1]+data[4][0]+data[4][1]);
    }
    
    public String[][] Datass(){
        return data;
    }
    private void btnregresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresoActionPerformed
        Inicio open = new Inicio();
        open.das(data);
        open.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnregresoActionPerformed

    private void cboficioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboficioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboficioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btnregreso;
    private javax.swing.JCheckBox cbcomida;
    private javax.swing.JCheckBox cblavado;
    private javax.swing.JCheckBox cboficio;
    private javax.swing.JCheckBox cbtrabajar;
    private javax.swing.JCheckBox cbvivo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
